### PR TITLE
Do not try to pipe Gzip responses with no body

### LINKED ISSUE #2045: HEAD requests with Node v5 have issues with gzipped content and fail.
This script reproduces the issue:

````js    
    var req = require('request');
    
    req({
        url: 'http://google.com',
        method: 'HEAD',
        headers: {},
        followAllRedirects: false,
        followRedirect: true,
        jar: true,
        timeout: 15000,
        gzip: true,
        rejectUnauthorized: false,
        strictSSL: true
    }, function (err, res, body) {
        if (err) {
            console.error(err.stack || err);
        }
    });
```

Steps to reproduce:

    aniket [/tmp/request-bug] -> node -v
    v5.1.0
    aniket [/tmp/request-bug] -> npm -v
    3.3.12
    aniket [/tmp/request-bug] -> cat node_modules/request/package.json| grep version
      "version": "2.69.0"
    aniket [/tmp/request-bug] -> node reproduce.js 
    Error: unexpected end of file
        at Zlib._handle.onerror (zlib.js:363:17)
    aniket [/tmp/request-bug] ->

### LINKED ISSUE #2177: Handling of empty responses when dealing with GZip
This is a continuation of the discussion in https://github.com/request/request/pull/2176

Basically, what should `request` do when a server returns an empty response with the `Content-Encoding` header set to `gzip`?

### PR DESCRIPTION
**Pull request by simov**
Fixes #2045
Fixes #2177

### CODE REVIEW

File: request.js [hunk 1]
```diff
@@ -921,7 +921,7 @@ Request.prototype.onRequestResponse = function (response) {
     })
 
     var responseContent
-    if (self.gzip) {
+    if (self.gzip && self.method !== 'HEAD') {
```
Comment (czardoz) [inline request.js]: This will fix the particular issue with HEAD requests, but will still cause issues if the response is empty for say a GET. A better way of handling would be to catch the Error from zlib.

**Comment by czardoz** [comment]
Thanks, @simov!

File: request.js (hunk 1 above)
Comment (simov) [inline request.js]: Figuring out if the response is empty beforehand would be great, will think about it. I would rather not use `try/catch` if there is some other way to detect the condition.

Comment (simov) [inline request.js]: Unfortunately there is no reliable way to determine upfront if the response body is empty. And in fact the error is thrown because the gzip content is invalid which may happen even if you have a body.
So at least we can do is forward the error events so that the user can handle them accordingly. Which means that you will receive an error when the request method is GET, the gzip option is true, and there is no response body.

Comment (simov) [inline request.js]: You can make assumption in your own layer, that when you receive that error under certain circumstances it may mean something, but as far as request is concerned the error should be forwarded.
I'm open for suggestion though.

Comment (simov) [inline request.js]: Wait, it's already like that, I got mislead.

Comment (simov) [inline request.js]: Anyway still this PR fixes the mentioned issue in the description which is the most common use case.

@czardoz you can open up another issue and point to this one, so we can have a discussion there.

Comment (czardoz) [inline request.js]: Done: #2177

**Comment by czardoz** [comment]
LGTM! :cake:

**Comment by simov** [comment]
Version 2.72 is out! :sparkles:
